In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('covid_toy.csv')

In [3]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [4]:
#Fever Column contains null values
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
df[df[['fever']].isnull().all(axis=1)]

,age,gender,fever,cough,city,has_covid
5,84,Female,NaN,Mild,Bangalore,Yes
7,20,Female,NaN,Strong,Mumbai,Yes
10,75,Female,NaN,Mild,Delhi,No
19,42,Female,NaN,Strong,Bangalore,Yes
25,23,Male,NaN,Mild,Mumbai,No
29,34,Female,NaN,Strong,Mumbai,Yes
41,82,Male,NaN,Mild,Kolkata,Yes
56,71,Male,NaN,Strong,Kolkata,No
91,38,Male,NaN,Mild,Delhi,Yes
94,79,Male,NaN,Strong,Kolkata,Yes


In [6]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [7]:
X_train

,age,gender,fever,cough,city
80,14,Female,99.0,Mild,Mumbai
41,82,Male,NaN,Mild,Kolkata
59,6,Female,104.0,Mild,Kolkata
10,75,Female,NaN,Mild,Delhi
45,72,Male,99.0,Mild,Bangalore
...,...,...,...,...,...
75,5,Male,102.0,Mild,Kolkata
60,24,Female,102.0,Strong,Bangalore
68,54,Female,104.0,Strong,Kolkata
70,68,Female,101.0,Strong,Delhi


In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline

In [37]:
# adding simple imputer to fever col

si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [40]:
#Null values will be replaced by mean of the column
X_train_fever

array([[ 99.        ],
       [100.91666667],
       [104.        ],
       [100.91666667],
       [ 99.        ],
       [102.        ],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [ 99.        ],
       [101.        ],
       [104.        ],
       [100.91666667],
       [100.        ],
       [100.        ],
       [102.        ],
       [104.        ],
       [ 99.        ],
       [101.        ],
       [101.        ],
       [ 99.        ],
       [102.        ],
       [104.        ],
       [ 99.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [103.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [100.91666667],
       [103.        ],
       [102

In [41]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])
X_test_cough.shape
X_train_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],

In [64]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [65]:
ohe.get_feature_names_out()

array(['gender_Male', 'city_Delhi', 'city_Kolkata', 'city_Mumbai'],
      dtype=object)

In [66]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [67]:
X_train_age.shape,X_train_fever.shape,X_train_gender_city.shape,X_train_cough.shape

((80, 1), (80, 1), (80, 4), (80, 1))

In [68]:
type(X_train_age),type(X_train_fever),type(X_train_gender_city),type(X_train_cough)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [71]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [73]:
X_test_transformed

array([[ 75.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 17.        , 104.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 19.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 25.        ,  99.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 26.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 12.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 16.        , 103.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 69.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 10.        ,  98.        ,   0.        ,   0.        ,
          1.    

In [ ]:
#Instead of doing one by one column transformation we can use ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [77]:
transformer.fit_transform(X_train).shape

(80, 7)

In [78]:
feature_names = transformer.get_feature_names_out()
print(feature_names)

['tnf1__fever' 'tnf2__cough' 'tnf3__gender_Male' 'tnf3__city_Delhi'
 'tnf3__city_Kolkata' 'tnf3__city_Mumbai' 'remainder__age']
